version: "3.8"

services:
  mongodb:
    image: mongo
    volumes:
      - data:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=max
    #   - MONGO_INITDB_ROOT_PASSWORD=secret
    # env_file:
    #   - ./config/mongodb.env


  backend:
    build: ./backend
    ports:
      - '5000:5000'
    # volumes:
    #   - ./backend:/app
    #   - /app/node_modules
    env_file:
      - ./backend/config/config.env
    depends_on:
      - mongodb


  frontend:
    build: ./client
    ports:
      - '3000:3000'
    # volumes:
    #   - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend


volumes:
  data: